package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 21 16:49:38 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DutyAllowanceLinesVoRowImpl extends ViewRowImpl {

    public static final int ENTITY_DUTYALLOWANCELINES_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AllowanceAmount,
        AllowanceDays,
        AllowanceRate,
        AllowanceType,
        Comments,
        CreatedBy,
        CreationDate,
        EdAllowanceLineId,
        EndDate,
        ExtraDutyAllowanceId,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        StartDate,
        Trans_AllowanceType,
        DutyAllow_ROVO,
        ExtraDutyAllowanceROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ALLOWANCEAMOUNT = AttributesEnum.AllowanceAmount.index();
    public static final int ALLOWANCEDAYS = AttributesEnum.AllowanceDays.index();
    public static final int ALLOWANCERATE = AttributesEnum.AllowanceRate.index();
    public static final int ALLOWANCETYPE = AttributesEnum.AllowanceType.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int EDALLOWANCELINEID = AttributesEnum.EdAllowanceLineId.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int EXTRADUTYALLOWANCEID = AttributesEnum.ExtraDutyAllowanceId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TRANS_ALLOWANCETYPE = AttributesEnum.Trans_AllowanceType.index();
    public static final int DUTYALLOW_ROVO = AttributesEnum.DutyAllow_ROVO.index();
    public static final int EXTRADUTYALLOWANCEROVO = AttributesEnum.ExtraDutyAllowanceROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DutyAllowanceLinesVoRowImpl() {
    }

    /**
     * Gets DutyAllowanceLines_EO entity object.
     * @return the DutyAllowanceLines_EO
     */
    public EntityImpl getDutyAllowanceLines_EO() {
        return (EntityImpl) getEntity(ENTITY_DUTYALLOWANCELINES_EO);
    }

    /**
     * Gets the attribute value for ALLOWANCE_AMOUNT using the alias name AllowanceAmount.
     * @return the ALLOWANCE_AMOUNT
     */
    public BigDecimal getAllowanceAmount() {
        return (BigDecimal) getAttributeInternal(ALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE_AMOUNT using the alias name AllowanceAmount.
     * @param value value to set the ALLOWANCE_AMOUNT
     */
    public void setAllowanceAmount(BigDecimal value) {
        setAttributeInternal(ALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for ALLOWANCE_DAYS using the alias name AllowanceDays.
     * @return the ALLOWANCE_DAYS
     */
    public BigDecimal getAllowanceDays() {
        return (BigDecimal) getAttributeInternal(ALLOWANCEDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE_DAYS using the alias name AllowanceDays.
     * @param value value to set the ALLOWANCE_DAYS
     */
    public void setAllowanceDays(BigDecimal value) {
        setAttributeInternal(ALLOWANCEDAYS, value);
    }

    /**
     * Gets the attribute value for ALLOWANCE_RATE using the alias name AllowanceRate.
     * @return the ALLOWANCE_RATE
     */
    public BigDecimal getAllowanceRate() {
        return (BigDecimal) getAttributeInternal(ALLOWANCERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE_RATE using the alias name AllowanceRate.
     * @param value value to set the ALLOWANCE_RATE
     */
    public void setAllowanceRate(BigDecimal value) {
        setAttributeInternal(ALLOWANCERATE, value);
    }

    /**
     * Gets the attribute value for ALLOWANCE_TYPE using the alias name AllowanceType.
     * @return the ALLOWANCE_TYPE
     */
    public String getAllowanceType() {
        return (String) getAttributeInternal(ALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE_TYPE using the alias name AllowanceType.
     * @param value value to set the ALLOWANCE_TYPE
     */
    public void setAllowanceType(String value) {
        setAttributeInternal(ALLOWANCETYPE, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for ED_ALLOWANCE_LINE_ID using the alias name EdAllowanceLineId.
     * @return the ED_ALLOWANCE_LINE_ID
     */
    public BigDecimal getEdAllowanceLineId() {
        return (BigDecimal) getAttributeInternal(EDALLOWANCELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ED_ALLOWANCE_LINE_ID using the alias name EdAllowanceLineId.
     * @param value value to set the ED_ALLOWANCE_LINE_ID
     */
    public void setEdAllowanceLineId(BigDecimal value) {
        setAttributeInternal(EDALLOWANCELINEID, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for EXTRA_DUTY_ALLOWANCE_ID using the alias name ExtraDutyAllowanceId.
     * @return the EXTRA_DUTY_ALLOWANCE_ID
     */
    public BigDecimal getExtraDutyAllowanceId() {
        return (BigDecimal) getAttributeInternal(EXTRADUTYALLOWANCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_DUTY_ALLOWANCE_ID using the alias name ExtraDutyAllowanceId.
     * @param value value to set the EXTRA_DUTY_ALLOWANCE_ID
     */
    public void setExtraDutyAllowanceId(BigDecimal value) {
        setAttributeInternal(EXTRADUTYALLOWANCEID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AllowanceType.
     * @return the Trans_AllowanceType
     */
    public String getTrans_AllowanceType() {
        String type = null;
                String name = null;
                if (getAllowanceType() != null) {
                    type = getAllowanceType();
                    Row[] orgRows;
                    orgRows = getExtraDutyAllowanceROVO().getFilteredRows("Allowance", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("Allowance").toString();
                    }
                    return name;
        
                } else {
                    return (String) getAttributeInternal(TRANS_ALLOWANCETYPE);
                }
        //return (String) getAttributeInternal(TRANS_ALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AllowanceType.
     * @param value value to set the  Trans_AllowanceType
     */
    public void setTrans_AllowanceType(String value) {
        setAttributeInternal(TRANS_ALLOWANCETYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DutyAllow_ROVO.
     */
    public RowSet getDutyAllow_ROVO() {
        return (RowSet) getAttributeInternal(DUTYALLOW_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ExtraDutyAllowanceROVO.
     */
    public RowSet getExtraDutyAllowanceROVO() {
        return (RowSet) getAttributeInternal(EXTRADUTYALLOWANCEROVO);
    }
}

