package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 29 10:58:49 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XssshrKbcPeriodVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XssshrKbcPeriodVOImpl() {
    }
}

