package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.XssshrKbcPeriodEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 29 10:58:48 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XssshrKbcPeriodVORowImpl extends ViewRowImpl {
    public static final int ENTITY_XSSSHRKBCPERIODEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        KbcPeriodId,
        KnowBuddyCareId,
        EffectiveStartDate,
        EffectiveEndDate,
        CurrentAvailablityInd,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int KBCPERIODID = AttributesEnum.KbcPeriodId.index();
    public static final int KNOWBUDDYCAREID = AttributesEnum.KnowBuddyCareId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int CURRENTAVAILABLITYIND = AttributesEnum.CurrentAvailablityInd.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XssshrKbcPeriodVORowImpl() {
    }

    /**
     * Gets XssshrKbcPeriodEO entity object.
     * @return the XssshrKbcPeriodEO
     */
    public XssshrKbcPeriodEOImpl getXssshrKbcPeriodEO() {
        return (XssshrKbcPeriodEOImpl) getEntity(ENTITY_XSSSHRKBCPERIODEO);
    }

    /**
     * Gets the attribute value for KBC_PERIOD_ID using the alias name KbcPeriodId.
     * @return the KBC_PERIOD_ID
     */
    public BigDecimal getKbcPeriodId() {
        return (BigDecimal) getAttributeInternal(KBCPERIODID);
    }

    /**
     * Sets <code>value</code> as attribute value for KBC_PERIOD_ID using the alias name KbcPeriodId.
     * @param value value to set the KBC_PERIOD_ID
     */
    public void setKbcPeriodId(BigDecimal value) {
        setAttributeInternal(KBCPERIODID, value);
    }

    /**
     * Gets the attribute value for KNOW_BUDDY_CARE_ID using the alias name KnowBuddyCareId.
     * @return the KNOW_BUDDY_CARE_ID
     */
    public String getKnowBuddyCareId() {
        return (String) getAttributeInternal(KNOWBUDDYCAREID);
    }

    /**
     * Sets <code>value</code> as attribute value for KNOW_BUDDY_CARE_ID using the alias name KnowBuddyCareId.
     * @param value value to set the KNOW_BUDDY_CARE_ID
     */
    public void setKnowBuddyCareId(String value) {
        setAttributeInternal(KNOWBUDDYCAREID, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Timestamp getEffectiveStartDate() {
        return (Timestamp) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Timestamp value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Timestamp getEffectiveEndDate() {
        return (Timestamp) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Timestamp value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for CURRENT_AVAILABLITY_IND using the alias name CurrentAvailablityInd.
     * @return the CURRENT_AVAILABLITY_IND
     */
    public String getCurrentAvailablityInd() {
        return (String) getAttributeInternal(CURRENTAVAILABLITYIND);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_AVAILABLITY_IND using the alias name CurrentAvailablityInd.
     * @param value value to set the CURRENT_AVAILABLITY_IND
     */
    public void setCurrentAvailablityInd(String value) {
        setAttributeInternal(CURRENTAVAILABLITYIND, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }
}

