package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.XxsshrKnowBuddyCareEOImpl;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 10 13:42:32 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrKnowBuddyCareVORowImpl extends ViewRowImpl {
    public static final int ENTITY_XXSSHRKNOWBUDDYCAREEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        KnowBuddyCareId,
        KnowBuddyCareNo,
        PersonId,
        BusinessUnitId,
        TransactionDate,
        Comments,
        ApprovalStatus,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        PayrollBatchName,
        SoaFlowid,
        ErrorMsg,
        PreviousApprover,
        NextApprover,
        ApproverComments,
        Name_Trns,
        Number_Trns,
        Email_Trns,
        Group_Trns,
        Trans_Cadre,
        Trans_Value,
        Trans_AssignmentType,
        SubscriptionFlag,
        SubscriptionStatus,
        XssshrKbcPeriodVO,
        Employee_View_ROVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int KNOWBUDDYCAREID = AttributesEnum.KnowBuddyCareId.index();
    public static final int KNOWBUDDYCARENO = AttributesEnum.KnowBuddyCareNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int PREVIOUSAPPROVER = AttributesEnum.PreviousApprover.index();
    public static final int NEXTAPPROVER = AttributesEnum.NextApprover.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int NAME_TRNS = AttributesEnum.Name_Trns.index();
    public static final int NUMBER_TRNS = AttributesEnum.Number_Trns.index();
    public static final int EMAIL_TRNS = AttributesEnum.Email_Trns.index();
    public static final int GROUP_TRNS = AttributesEnum.Group_Trns.index();
    public static final int TRANS_CADRE = AttributesEnum.Trans_Cadre.index();
    public static final int TRANS_VALUE = AttributesEnum.Trans_Value.index();
    public static final int TRANS_ASSIGNMENTTYPE = AttributesEnum.Trans_AssignmentType.index();
    public static final int SUBSCRIPTIONFLAG = AttributesEnum.SubscriptionFlag.index();
    public static final int SUBSCRIPTIONSTATUS = AttributesEnum.SubscriptionStatus.index();
    public static final int XSSSHRKBCPERIODVO = AttributesEnum.XssshrKbcPeriodVO.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrKnowBuddyCareVORowImpl() {
    }

    /**
     * Gets XxsshrKnowBuddyCareEO entity object.
     * @return the XxsshrKnowBuddyCareEO
     */
    public XxsshrKnowBuddyCareEOImpl getXxsshrKnowBuddyCareEO() {
        return (XxsshrKnowBuddyCareEOImpl) getEntity(ENTITY_XXSSHRKNOWBUDDYCAREEO);
    }

    /**
     * Gets the attribute value for KNOW_BUDDY_CARE_ID using the alias name KnowBuddyCareId.
     * @return the KNOW_BUDDY_CARE_ID
     */
    public BigDecimal getKnowBuddyCareId() {
        return (BigDecimal) getAttributeInternal(KNOWBUDDYCAREID);
    }

    /**
     * Sets <code>value</code> as attribute value for KNOW_BUDDY_CARE_ID using the alias name KnowBuddyCareId.
     * @param value value to set the KNOW_BUDDY_CARE_ID
     */
    public void setKnowBuddyCareId(BigDecimal value) {
        setAttributeInternal(KNOWBUDDYCAREID, value);
    }

    /**
     * Gets the attribute value for KNOW_BUDDY_CARE_NO using the alias name KnowBuddyCareNo.
     * @return the KNOW_BUDDY_CARE_NO
     */
    public String getKnowBuddyCareNo() {
        return (String) getAttributeInternal(KNOWBUDDYCARENO);
    }

    /**
     * Sets <code>value</code> as attribute value for KNOW_BUDDY_CARE_NO using the alias name KnowBuddyCareNo.
     * @param value value to set the KNOW_BUDDY_CARE_NO
     */
    public void setKnowBuddyCareNo(String value) {
        setAttributeInternal(KNOWBUDDYCARENO, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @return the TRANSACTION_DATE
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @param value value to set the TRANSACTION_DATE
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @return the PREVIOUS_APPROVER
     */
    public String getPreviousApprover() {
        return (String) getAttributeInternal(PREVIOUSAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @param value value to set the PREVIOUS_APPROVER
     */
    public void setPreviousApprover(String value) {
        setAttributeInternal(PREVIOUSAPPROVER, value);
    }

    /**
     * Gets the attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @return the NEXT_APPROVER
     */
    public String getNextApprover() {
        return (String) getAttributeInternal(NEXTAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @param value value to set the NEXT_APPROVER
     */
    public void setNextApprover(String value) {
        setAttributeInternal(NEXTAPPROVER, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name_Trns.
     * @return the Name_Trns
     */
    public String getName_Trns() {
        BigDecimal type = null;
                String name = null;
                if (getPersonId() != null) {
                    type = (BigDecimal) getPersonId();
                    Row[] orgRows;
                    orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("DisplayName").toString();
                        System.out.println("name ------- " + name);
                    }
                    return name;
                } else {

                    return (String) getAttributeInternal(NAME_TRNS);
                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name_Trns.
     * @param value value to set the  Name_Trns
     */
    public void setName_Trns(String value) {
        setAttributeInternal(NAME_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trns.
     * @return the Number_Trns
     */
    public String getNumber_Trns() {
        BigDecimal type = null;
                String name = null;
                if (getPersonId() != null) {
                    type = (BigDecimal) getPersonId();
                    Row[] orgRows;
                    orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("PersonNumber").toString();
                    }
                    return name;
                } else {
                    return (String) getAttributeInternal(NUMBER_TRNS);

                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trns.
     * @param value value to set the  Number_Trns
     */
    public void setNumber_Trns(String value) {
        setAttributeInternal(NUMBER_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trns.
     * @return the Email_Trns
     */
    public String getEmail_Trns() {
        BigDecimal type = null;
               String name = null;
               if (getPersonId() != null) {
                   type = (BigDecimal) getPersonId();
                   Row[] orgRows;
                   orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                   if (orgRows.length > 0) {
                       name = orgRows[0].getAttribute("EmailAddress").toString();
                   }
                   return name;
               } else {
                   return (String) getAttributeInternal(EMAIL_TRNS);
               }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trns.
     * @param value value to set the  Email_Trns
     */
    public void setEmail_Trns(String value) {
        setAttributeInternal(EMAIL_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trns.
     * @return the Group_Trns
     */
    public String getGroup_Trns() {
        BigDecimal type = null;
                String name = null;
                if (getPersonId() != null) {
                    type = (BigDecimal) getPersonId();
                    Row[] orgRows;
                    orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("BusinessUnitName").toString();
                    }
                    return name;
                } else {
                    return (String) getAttributeInternal(GROUP_TRNS);
                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trns.
     * @param value value to set the  Group_Trns
     */
    public void setGroup_Trns(String value) {
        setAttributeInternal(GROUP_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Cadre.
     * @return the Trans_Cadre
     */
    public String getTrans_Cadre() {
        BigDecimal type = null;
                String name = null;
                if (getPersonId() != null) {
                    type = (BigDecimal) getPersonId();
                    Row[] orgRows;
                    orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("Cadre").toString();
                    }
                    return name;
                } else {

                    return (String) getAttributeInternal(TRANS_CADRE);
                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Cadre.
     * @param value value to set the  Trans_Cadre
     */
    public void setTrans_Cadre(String value) {
        setAttributeInternal(TRANS_CADRE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Value.
     * @return the Trans_Value
     */
    public String getTrans_Value() {
        BigDecimal type = null;
               String name = null;
               if (getPersonId() != null) {
                   type = (BigDecimal) getPersonId();
                   Row[] orgRows;
                   orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                   if (orgRows.length > 0) {
                       name = orgRows[0].getAttribute("DepartmentName").toString();
                   }
                   System.out.println("Dept name ---------- " + name);
                   return name;
               } else {

                   return (String) getAttributeInternal(TRANS_VALUE);
               }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Value.
     * @param value value to set the  Trans_Value
     */
    public void setTrans_Value(String value) {
        setAttributeInternal(TRANS_VALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssignmentType.
     * @return the Trans_AssignmentType
     */
    public String getTrans_AssignmentType() {
        BigDecimal type = null;
                String name = null;
                if (getPersonId() != null) {
                    type = (BigDecimal) getPersonId();
                    Row[] orgRows;
                    orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
                    if (orgRows.length > 0) {
                        name = orgRows[0].getAttribute("PersonType").toString();
                    }
                    return name;
                } else {
                    return (String) getAttributeInternal(TRANS_ASSIGNMENTTYPE);
                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssignmentType.
     * @param value value to set the  Trans_AssignmentType
     */
    public void setTrans_AssignmentType(String value) {
        setAttributeInternal(TRANS_ASSIGNMENTTYPE, value);
    }

    /**
     * Gets the attribute value for SUBSCRIPTION_FLAG using the alias name SubscriptionFlag.
     * @return the SUBSCRIPTION_FLAG
     */
    public String getSubscriptionFlag() {
        return (String) getAttributeInternal(SUBSCRIPTIONFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBSCRIPTION_FLAG using the alias name SubscriptionFlag.
     * @param value value to set the SUBSCRIPTION_FLAG
     */
    public void setSubscriptionFlag(String value) {
        setAttributeInternal(SUBSCRIPTIONFLAG, value);
    }

    /**
     * Gets the attribute value for SUBSCRIPTION_STATUS using the alias name SubscriptionStatus.
     * @return the SUBSCRIPTION_STATUS
     */
    public String getSubscriptionStatus() {
        return (String) getAttributeInternal(SUBSCRIPTIONSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBSCRIPTION_STATUS using the alias name SubscriptionStatus.
     * @param value value to set the SUBSCRIPTION_STATUS
     */
    public void setSubscriptionStatus(String value) {
        setAttributeInternal(SUBSCRIPTIONSTATUS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XssshrKbcPeriodVO.
     */
    public RowIterator getXssshrKbcPeriodVO() {
        return (RowIterator) getAttributeInternal(XSSSHRKBCPERIODVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }
}

