package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 25 12:29:20 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSSHR_TAP_EMP_LINES_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_XXSSHR_TAP_EMP_LINES_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AvailableFlag,
        CreatedBy,
        CreationDate,
        DonationAmount,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        Months,
        TapEmpFormId,
        TapEmpLineId,
        LookUp_ROVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AVAILABLEFLAG = AttributesEnum.AvailableFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DONATIONAMOUNT = AttributesEnum.DonationAmount.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int MONTHS = AttributesEnum.Months.index();
    public static final int TAPEMPFORMID = AttributesEnum.TapEmpFormId.index();
    public static final int TAPEMPLINEID = AttributesEnum.TapEmpLineId.index();
    public static final int LOOKUP_ROVO1 = AttributesEnum.LookUp_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXSSHR_TAP_EMP_LINES_VORowImpl() {
    }

    /**
     * Gets XXSSHR_TAP_EMP_LINES_EO entity object.
     * @return the XXSSHR_TAP_EMP_LINES_EO
     */
    public EntityImpl getXXSSHR_TAP_EMP_LINES_EO() {
        return (EntityImpl) getEntity(ENTITY_XXSSHR_TAP_EMP_LINES_EO);
    }

    /**
     * Gets the attribute value for AVAILABLE_FLAG using the alias name AvailableFlag.
     * @return the AVAILABLE_FLAG
     */
    public String getAvailableFlag() {
        return (String) getAttributeInternal(AVAILABLEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for AVAILABLE_FLAG using the alias name AvailableFlag.
     * @param value value to set the AVAILABLE_FLAG
     */
    public void setAvailableFlag(String value) {
        setAttributeInternal(AVAILABLEFLAG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for DONATION_AMOUNT using the alias name DonationAmount.
     * @return the DONATION_AMOUNT
     */
    public BigDecimal getDonationAmount() {
        return (BigDecimal) getAttributeInternal(DONATIONAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DONATION_AMOUNT using the alias name DonationAmount.
     * @param value value to set the DONATION_AMOUNT
     */
    public void setDonationAmount(BigDecimal value) {
        setAttributeInternal(DONATIONAMOUNT, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for MONTHS using the alias name Months.
     * @return the MONTHS
     */
    public String getMonths() {
        return (String) getAttributeInternal(MONTHS);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTHS using the alias name Months.
     * @param value value to set the MONTHS
     */
    public void setMonths(String value) {
        setAttributeInternal(MONTHS, value);
    }

    /**
     * Gets the attribute value for TAP_EMP_FORM_ID using the alias name TapEmpFormId.
     * @return the TAP_EMP_FORM_ID
     */
    public BigDecimal getTapEmpFormId() {
        return (BigDecimal) getAttributeInternal(TAPEMPFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAP_EMP_FORM_ID using the alias name TapEmpFormId.
     * @param value value to set the TAP_EMP_FORM_ID
     */
    public void setTapEmpFormId(BigDecimal value) {
        setAttributeInternal(TAPEMPFORMID, value);
    }

    /**
     * Gets the attribute value for TAP_EMP_LINE_ID using the alias name TapEmpLineId.
     * @return the TAP_EMP_LINE_ID
     */
    public BigDecimal getTapEmpLineId() {
        return (BigDecimal) getAttributeInternal(TAPEMPLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAP_EMP_LINE_ID using the alias name TapEmpLineId.
     * @param value value to set the TAP_EMP_LINE_ID
     */
    public void setTapEmpLineId(BigDecimal value) {
        setAttributeInternal(TAPEMPLINEID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookUp_ROVO1.
     */
    public RowSet getLookUp_ROVO1() {
        return (RowSet) getAttributeInternal(LOOKUP_ROVO1);
    }
}

