package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 24 10:05:36 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSSHR_TAP_EMP_FORM_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXSSHR_TAP_EMP_FORM_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalStatus,
        ApproverComments,
        BusinessUnitId,
        Comments,
        CreatedBy,
        CreationDate,
        ErrorMsg,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PayrollBatchName,
        PersonId,
        SoaFlowid,
        TapEmpFormId,
        TapEmpFormNo,
        TransactionDate,
        Name_Trns,
        Number_Trns,
        Email_Trns,
        Group_Trns,
        Trans_Cadre,
        Trans_Value,
        Trans_AssignmentType,
        XXSSHR_TAP_EMP_LINES_VO,
        Employee_View_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int TAPEMPFORMID = AttributesEnum.TapEmpFormId.index();
    public static final int TAPEMPFORMNO = AttributesEnum.TapEmpFormNo.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int NAME_TRNS = AttributesEnum.Name_Trns.index();
    public static final int NUMBER_TRNS = AttributesEnum.Number_Trns.index();
    public static final int EMAIL_TRNS = AttributesEnum.Email_Trns.index();
    public static final int GROUP_TRNS = AttributesEnum.Group_Trns.index();
    public static final int TRANS_CADRE = AttributesEnum.Trans_Cadre.index();
    public static final int TRANS_VALUE = AttributesEnum.Trans_Value.index();
    public static final int TRANS_ASSIGNMENTTYPE = AttributesEnum.Trans_AssignmentType.index();
    public static final int XXSSHR_TAP_EMP_LINES_VO = AttributesEnum.XXSSHR_TAP_EMP_LINES_VO.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXSSHR_TAP_EMP_FORM_VORowImpl() {
    }

    /**
     * Gets XXSSHR_TAP_EMP_FORM_EO entity object.
     * @return the XXSSHR_TAP_EMP_FORM_EO
     */
    public EntityImpl getXXSSHR_TAP_EMP_FORM_EO() {
        return (EntityImpl) getEntity(ENTITY_XXSSHR_TAP_EMP_FORM_EO);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for TAP_EMP_FORM_ID using the alias name TapEmpFormId.
     * @return the TAP_EMP_FORM_ID
     */
    public BigDecimal getTapEmpFormId() {
        return (BigDecimal) getAttributeInternal(TAPEMPFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for TAP_EMP_FORM_ID using the alias name TapEmpFormId.
     * @param value value to set the TAP_EMP_FORM_ID
     */
    public void setTapEmpFormId(BigDecimal value) {
        setAttributeInternal(TAPEMPFORMID, value);
    }

    /**
     * Gets the attribute value for TAP_EMP_FORM_NO using the alias name TapEmpFormNo.
     * @return the TAP_EMP_FORM_NO
     */
    public String getTapEmpFormNo() {
        return (String) getAttributeInternal(TAPEMPFORMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TAP_EMP_FORM_NO using the alias name TapEmpFormNo.
     * @param value value to set the TAP_EMP_FORM_NO
     */
    public void setTapEmpFormNo(String value) {
        setAttributeInternal(TAPEMPFORMNO, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @return the TRANSACTION_DATE
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @param value value to set the TRANSACTION_DATE
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name_Trns.
     * @return the Name_Trns
     */
    public String getName_Trns() {

        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("DisplayName").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(NAME_TRNS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name_Trns.
     * @param value value to set the  Name_Trns
     */
    public void setName_Trns(String value) {
        setAttributeInternal(NAME_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trns.
     * @return the Number_Trns
     */
    public String getNumber_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonNumber").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(NUMBER_TRNS);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trns.
     * @param value value to set the  Number_Trns
     */
    public void setNumber_Trns(String value) {
        setAttributeInternal(NUMBER_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trns.
     * @return the Email_Trns
     */
    public String getEmail_Trns() {
                                                        
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
        type = (BigDecimal)getPersonId();
        Row[] orgRows;
        orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
        if (orgRows.length > 0) {
        name = orgRows[0].getAttribute("EmailAddress").toString();
        }
        return name;
                                } else {
        return (String) getAttributeInternal(EMAIL_TRNS);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trns.
     * @param value value to set the  Email_Trns
     */
    public void setEmail_Trns(String value) {
        setAttributeInternal(EMAIL_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trns.
     * @return the Group_Trns
     */
    public String getGroup_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("BusinessUnitName").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(GROUP_TRNS);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trns.
     * @param value value to set the  Group_Trns
     */
    public void setGroup_Trns(String value) {
        setAttributeInternal(GROUP_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Cadre.
     * @return the Trans_Cadre
     */
    public String getTrans_Cadre() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("Cadre").toString();
            }
            return name;
        } else {

        return (String) getAttributeInternal(TRANS_CADRE);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Cadre.
     * @param value value to set the  Trans_Cadre
     */
    public void setTrans_Cadre(String value) {
        setAttributeInternal(TRANS_CADRE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Ttans_Value.
     * @return the Ttans_Value
     */
    public String getTrans_Value() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("FullPartTime").toString();
            }
            return name;
        } else {


        return (String) getAttributeInternal(TRANS_VALUE);}
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Value.
     * @param value value to set the  Trans_Value
     */
    public void setTrans_Value(String value) {
        setAttributeInternal(TRANS_VALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssignmentType.
     * @return the Trans_AssignmentType
     */
    public String getTrans_AssignmentType() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("AssignmentType").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(TRANS_ASSIGNMENTTYPE);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssignmentType.
     * @param value value to set the  Trans_AssignmentType
     */
    public void setTrans_AssignmentType(String value) {
        setAttributeInternal(TRANS_ASSIGNMENTTYPE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XXSSHR_TAP_EMP_LINES_VO.
     */
    public RowIterator getXXSSHR_TAP_EMP_LINES_VO() {
        return (RowIterator) getAttributeInternal(XXSSHR_TAP_EMP_LINES_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }
}

