package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 21 16:49:41 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DutyAllowanceLinesVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DutyAllowanceLinesVoImpl() {
    }
}

