package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 27 23:49:15 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DutyAllowance_EOImpl extends EntityImpl {
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        RowIterator lines = getDutyAllowanceLines_EO();
              
               while (lines.hasNext()) {
                   //Delete all bupaRs
           lines.next().remove();
               }

        super.remove();
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ExtraDutyAllowanceId,
        ExtraDutyAllowanceNo,
        PersonId,
        BusinessUnitId,
        TransactionDate,
        Comments,
        ApprovalStatus,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        TotAllowanceAmount,
        ApproverComments,
        PreviousApprover,
        NextApprover,
        DutyAllowanceLines_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXTRADUTYALLOWANCEID = AttributesEnum.ExtraDutyAllowanceId.index();
    public static final int EXTRADUTYALLOWANCENO = AttributesEnum.ExtraDutyAllowanceNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int TOTALLOWANCEAMOUNT = AttributesEnum.TotAllowanceAmount.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int PREVIOUSAPPROVER = AttributesEnum.PreviousApprover.index();
    public static final int NEXTAPPROVER = AttributesEnum.NextApprover.index();
    public static final int DUTYALLOWANCELINES_EO = AttributesEnum.DutyAllowanceLines_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DutyAllowance_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.DutyAllowance_EO");
    }


    /**
     * Gets the attribute value for ExtraDutyAllowanceId, using the alias name ExtraDutyAllowanceId.
     * @return the value of ExtraDutyAllowanceId
     */
    public BigDecimal getExtraDutyAllowanceId() {
        return (BigDecimal) getAttributeInternal(EXTRADUTYALLOWANCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraDutyAllowanceId.
     * @param value value to set the ExtraDutyAllowanceId
     */
    public void setExtraDutyAllowanceId(BigDecimal value) {
        setAttributeInternal(EXTRADUTYALLOWANCEID, value);
    }

    /**
     * Gets the attribute value for ExtraDutyAllowanceNo, using the alias name ExtraDutyAllowanceNo.
     * @return the value of ExtraDutyAllowanceNo
     */
    public String getExtraDutyAllowanceNo() {
        return (String) getAttributeInternal(EXTRADUTYALLOWANCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraDutyAllowanceNo.
     * @param value value to set the ExtraDutyAllowanceNo
     */
    public void setExtraDutyAllowanceNo(String value) {
        setAttributeInternal(EXTRADUTYALLOWANCENO, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BusinessUnitId, using the alias name BusinessUnitId.
     * @return the value of BusinessUnitId
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitId.
     * @param value value to set the BusinessUnitId
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the value of TransactionDate
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }


    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ApprovalStatus, using the alias name ApprovalStatus.
     * @return the value of ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalStatus.
     * @param value value to set the ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for TotAllowanceAmount, using the alias name TotAllowanceAmount.
     * @return the value of TotAllowanceAmount
     */
    public BigDecimal getTotAllowanceAmount() {
        return (BigDecimal) getAttributeInternal(TOTALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotAllowanceAmount.
     * @param value value to set the TotAllowanceAmount
     */
    public void setTotAllowanceAmount(BigDecimal value) {
        setAttributeInternal(TOTALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for ApproverComments, using the alias name ApproverComments.
     * @return the value of ApproverComments
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApproverComments.
     * @param value value to set the ApproverComments
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for PreviousApprover, using the alias name PreviousApprover.
     * @return the value of PreviousApprover
     */
    public String getPreviousApprover() {
        return (String) getAttributeInternal(PREVIOUSAPPROVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousApprover.
     * @param value value to set the PreviousApprover
     */
    public void setPreviousApprover(String value) {
        setAttributeInternal(PREVIOUSAPPROVER, value);
    }

    /**
     * Gets the attribute value for NextApprover, using the alias name NextApprover.
     * @return the value of NextApprover
     */
    public String getNextApprover() {
        return (String) getAttributeInternal(NEXTAPPROVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextApprover.
     * @param value value to set the NextApprover
     */
    public void setNextApprover(String value) {
        setAttributeInternal(NEXTAPPROVER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDutyAllowanceLines_EO() {
        return (RowIterator) getAttributeInternal(DUTYALLOWANCELINES_EO);
    }

    /**
     * @param extraDutyAllowanceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal extraDutyAllowanceId) {
        return new Key(new Object[] { extraDutyAllowanceId });
    }


}

