package model.am.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 23 10:27:19 IST 2019
// ---------------------------------------------------------------------
public interface Oando_AM extends ApplicationModule {
    void filterUser();

    BigDecimal getPersonId(String userName);

    String getAssignmentType();
}

